### ISSUE TITLE
error: uncaughtException: Cannot find module '/src/.config.js'

### ISSUE THREAD

**Issue by kapoorlakshya** [Verkurkie/timings-docker#24]
I am seeing the following error when I run the docker image:

```
timings          | error: uncaughtException: Cannot find module '/src/.config.js' date=Wed Feb 07 2018 00:50:55 GMT+0000 (UTC), pid=1, uid=0, gid=0, cwd=/src, execPath=/usr/local/bin/node, version=v8.4.0, argv=[/usr/local/bin/node, /src/server.js], rss=58322944, heapTotal=39010304, heapUsed=24438584, external=49620, loadavg=[1.2900390625, 0.595703125, 0.400390625], uptime=2980, trace=[column=15, file=module.js, function=Module._resolveFilename, line=489, method=_resolveFilename, native=false, column=25, file=module.js, function=Module._load, line=439, method=_load, native=false, column=17, file=module.js, function=Module.require, line=517, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=19, file=/src/server.js, function=null, line=38, method=null, native=false, column=30, file=module.js, function=Module._compile, line=573, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=584, method=.js, native=false, column=32, file=module.js, function=Module.load, line=507, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=470, method=null, native=false, column=3, file=module.js, function=Module._load, line=462, method=_load, native=false], stack=[Error: Cannot find module '/src/.config.js',     at Function.Module._resolveFilename (module.js:489:15),     at Function.Module._load (module.js:439:25),     at Module.require (module.js:517:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (/src/server.js:38:19),     at Module._compile (module.js:573:30),     at Object.Module._extensions..js (module.js:584:10),     at Module.load (module.js:507:32),     at tryModuleLoad (module.js:470:12),     at Function.Module._load (module.js:462:3)]
timings exited with code 0
```

Kibana and EC work fine, but unable to access `timings` @ localhost:80.

```
$ docker-compose images
WARNING: The CONFIGFILE variable is not set. Defaulting to a blank string.
  Container                      Repository                      Tag      Image Id      Size
---------------------------------------------------------------------------------------------
elasticsearch   docker.elastic.co/elasticsearch/elasticsearch   5.6.2   59b11c02b218   626 MB
kibana          docker.elastic.co/kibana/kibana                 5.6.2   5b27c7e97a53   606 MB
timings         mverkerk/timings                                1.1.4   c4ae5568aed9   659 MB
```

**Comment by Verkurkie** [comment]
I noticed the warning message `The CONFIGFILE variable is not set. Defaulting to a blank string.` Have a look at this: https://github.com/Verkurkie/timings-docker#step-3-starting-up-the-api (create a config file and set the CONFIGFILE env variable)

**Comment by kapoorlakshya** [comment]
Cool, I did set the `CONFIGILE` variable and do not see the warning now. However, the error still exists.

**Comment by Verkurkie** [comment]
Just updated the repo. The docker-compose file and the API should now handle the config file properly. Please read the README.MD for instructions on how to use your own config file. Hope this works!

**Comment by Verkurkie** [comment]
Hey @kapoorlakshya - i will close this issue assuming things have been resolved. Feel free to open a new one if you are still having issues.
