### ISSUE TITLE
elasticsearch exited with code 1, timings exited with code 124

### ISSUE THREAD

**Issue by vikramvi** [Verkurkie/timings-docker#4]
Ubuntu 16.4

docker-compose up throws below error

```
Creating elasticsearch
Creating kibana
Creating timings
Attaching to elasticsearch, kibana, timings
timings          | wait-for-it.sh: waiting 30 seconds for elasticsearch:9200
elasticsearch    | [2017-10-26T09:54:53,424][INFO ][o.e.n.Node               ] [] initializing ...
elasticsearch    | [2017-10-26T09:54:53,444][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
elasticsearch    | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | Caused by: java.lang.IllegalStateException: Failed to create node environment
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:268) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	... 6 more
elasticsearch    | Caused by: java.nio.file.AccessDeniedException: /var/lib/elasticsearch/nodes
elasticsearch    | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
elasticsearch    | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
elasticsearch    | 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_141]
elasticsearch    | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_141]
elasticsearch    | 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_141]
elasticsearch    | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:221) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:265) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.2.jar:5.6.2]
elasticsearch    | 	... 6 more
elasticsearch exited with code 1
kibana           | {"type":"log","@timestamp":"2017-10-26T09:54:58Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes"}
timings          | wait-for-it.sh: timeout occurred after waiting 30 seconds for elasticsearch:9200
timings          | wait-for-it.sh: strict mode, refusing to execute subprocess
timings exited with code 124
kibana           | {"type":"log","@timestamp":"2017-10-26T09:56:19Z","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for kibana, stateSessionStorageRedirect, timelion and status_page complete in 80.69 seconds"}



```

**Comment by vikramvi** [comment]
Can you please clarify which OS do you use ? I'm facing quite a few issues on Ubuntu at the moment.

**Comment by vikramvi** [comment]
This issue is solved with below command ( help from my dev engineer )

`sudo chown -R ubuntuUserName:ubuntuUserName elasticsearch`

Can you please add these in FAQ section

**Comment by Verkurkie** [comment]
Thanks for the info! I have added the `FAQ` label so others can find it

**Comment by vikramvi** [comment]
The fix I mentioned may not be the best one.

Please refer to https://github.com/elastic/elasticsearch-docker/issues/21#issuecomment-339744214

**Comment by vikramvi** [comment]
added to https://github.com/Verkurkie/timings-docker/wiki/FAQ-page
